version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /root/gitea-docker/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      #- "3000:3000" <<==== Disabled because Gitea Web UI is reverse proxy by nginx container
      - "2222:22"
    networks:
      - gitea-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/gitea-docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/gitea-docker/nginx/certs:/etc/nginx/certs:ro
    networks:
      - gitea-network
    depends_on:
      - gitea
    restart: unless-stopped

  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    volumes:
      - /root/gitea-docker/loki:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - gitea-network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.4.1
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /root/gitea-docker/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - gitea-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - /root/gitea-docker/grafana:/var/lib/grafana
#    ports:
#      - "3000:3000"
    networks:
      - gitea-network

networks:
  gitea-network:
    driver: bridge
