server:
  address: tcp://0.0.0.0:9091/

log:
  level: debug

identity_validation:
  reset_password:
    jwt_secret: "eHMteYjcmARGOQSeAI2ZyJkw5WFUlghe/W+fFcPaU38="

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: gitea.example.com
      policy: one_factor

    - domain: grafana.example.com
      policy: one_factor

session:
  name: authelia_session
  secret: "NbyqDsmGTiunj3tIILbyZaJ+wcflpqeTwN5uA6FH0YQ="
  expiration: 3600
  inactivity: 300
  cookies:
    - domain: example.com
      authelia_url: https://auth.example.com
      default_redirection_url: https://gitea.example.com

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3
  encryption_key: "4re6g4z68Nnp01qm4b4QrYxw4U6/5HY9Tu57/Vg2kI8="

notifier:
  filesystem:
    filename: /config/notification.txt
